### ISSUE TITLE
View upcoming deadlines

### ISSUE THREAD

**Issue by gngster** [CS2103JAN2017-W15-B1/main#20]
List the tasks with deadlines in ascending order (nearest deadline first)

**Comment by ngshaohui** [comment]
Implemented but with bugs
The list does not appear to be able to be reordered

**Comment by ngshaohui** [comment]
Closed for milestone but will reopen for bug fix

**Comment by ngshaohui** [comment]
Reopened for bug fixing
It currently does not check for task completion status
