### ISSUE TITLE
Update user and developer guide

### ISSUE THREAD

**Issue by ngshaohui** [CS2103JAN2017-W15-B1/main#29]
Reorder the use cases by priority and remove the duplicates.

**Comment by ngshaohui** [comment]
Use case for changing UI is also missing

**Comment by ngshaohui** [comment]
Need to complete and reorder Appendix B according to Appendix A

**Comment by ngshaohui** [comment]
Diagrams need to be updated as they currently still say AddressBook

**Comment by ngshaohui** [comment]
Use the powerpoints located in main/docs/diagrams
Edit the diagrams and export them as images.

**Comment by le-minhphuc** [comment]
Last check before submission: Done
